export const GET_QUESTIONS_LIST = 'GET_QUESTIONS_LIST';
export const GET_MORE_QUESTIONS = 'GET_MORE_QUESTIONS';
export const ADD_QUESTION = 'ADD_QUESTION';
export const GET_HOT_QUESTIONS_LIST = 'GET_HOT_QUESTIONS_LIST';
export const GET_MOST_ACTIVE_USERS = 'GET_MOST_ACTIVE_USERS';

export const SET_USER = 'SET_USER';
export const GET_MY_QUESTIONS_LIST = 'GET_MY_QUESTIONS_LIST';
export const GET_MORE_MY_QUESTIONS = 'GET_MORE_MY_QUESTIONS';
